### ISSUE TITLE
Is UKI only suitable for Gaussian-like posterior distribution?

### ISSUE THREAD

**Issue by TanBendong** [PKU-CMEGroup/InverseProblems.jl#1]
Hi, Dr. Huang,

The performance of UKI is truly amazing, but it seems it is only suitable for Gaussian-like posterior distribution since we depict the parameter posterior distribution with its mean and covariance in a Gaussian distribution. Is my understanding right? Thanks!

Best,
Bendong

**Comment by Zhengyu-Huang** [comment]
Hi Bendong @TanBendong, 
Thank you for your interest！Yes, so far UKI only estimates mean and covariance of the posterior distribution.  It performs good when the posterior is close to Gaussian. I also studied when the posterior is close to Gaussian [here ](https://github.com/Zhengyu-Huang/InverseProblems.jl/blob/master/Lectures/Posterior.ipynb).

**Comment by TanBendong** [comment]
Thank you!
